// Package cli assembles the command-line surface of yonderllm.
//
// The package owns the composition root: it is the only place that turns a
// resolved [config.Config] into live provider adapters and hands them to a
// [session.Session]. Everything below it — provider, session, perm, config —
// stays free of flag parsing and of stdout.
//
// Commands are built with cobra for subcommand routing, suggestions, and shell
// completion, but the help and usage templates are replaced wholesale in
// help.go so the output is yonderllm's own rather than cobra's default shape.
package cli

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/signal"

	"github.com/spf13/cobra"

	"yonderllm/internal/config"
	"yonderllm/internal/perm"
)

// Version is the build identifier, overridable at link time with
// -ldflags "-X yonderllm/internal/cli.Version=...".
var Version = "dev"

// env carries everything a subcommand needs that is not one of its own flags:
// the streams to write to and the global flags, which are parsed once on the
// root command and shared by every child.
//
// Streams are fields rather than direct references to os.Stdout so that tests
// can run a command end to end and read what it produced.
type env struct {
	in     io.Reader
	out    io.Writer
	errOut io.Writer

	// Global flag values, bound on the root command. They are applied over
	// the loaded configuration by resolve, so a flag always beats a file.
	configPath string
	provider   string
	model      string
	mode       string
	maxTokens  int
	dailyCap   int
	yes        bool
	resume     string
	last       bool
	save       string
	noSave     bool
}

// resolve loads configuration and overlays the global flags.
//
// config.Load deliberately stops at the environment; applying flags here keeps
// the precedence chain — defaults, file, environment, flags — in one readable
// place and lets the config package stay unaware that flags exist.
func (e *env) resolve() (config.Config, error) {
	path := e.configPath
	if path == "" {
		p, err := config.Path()
		if err != nil {
			// A missing user config directory is not fatal: yonderllm
			// runs on defaults plus a key environment variable.
			path = ""
		} else {
			path = p
		}
	}

	cfg, err := config.Load(path)
	if err != nil {
		return config.Config{}, err
	}

	if e.provider != "" {
		cfg.Provider = e.provider
	}
	if e.model != "" {
		// The model flag names a model for whichever provider ends up
		// active, so it is applied after the provider flag.
		p, ok := cfg.Providers[cfg.Provider]
		if !ok {
			return config.Config{}, fmt.Errorf("provider %q is not configured", cfg.Provider)
		}
		p.Model = e.model
		cfg.Providers[cfg.Provider] = p
	}
	if e.mode != "" {
		cfg.Mode = e.mode
	}
	if e.maxTokens > 0 {
		cfg.MaxTokens = e.maxTokens
	}
	if e.dailyCap >= 0 {
		cfg.DailyCap = e.dailyCap
	}

	// The mode string reaches perm eventually; rejecting it here means an
	// invalid --mode fails before a request is spent.
	mode, err := perm.ParseMode(cfg.Mode)
	if err != nil {
		return config.Config{}, err
	}

	// --yes relaxes what agent mode would stop to ask about. It is refused
	// in the other modes rather than ignored: chat and code have limits that
	// are not up for negotiation, and a script that asked to skip approvals
	// should be told its request meant nothing rather than left believing
	// it was honoured. Refusing here spends no request.
	if e.yes && mode != perm.Agent {
		return config.Config{}, fmt.Errorf("--yes is only accepted in agent mode, and this run is in %s mode", mode)
	}

	if err := cfg.Validate(); err != nil {
		return config.Config{}, err
	}
	return cfg, nil
}

// newRoot builds the command tree against the given environment.
func newRoot(e *env) *cobra.Command {
	root := &cobra.Command{
		Use:   "yonderllm",
		Short: "Talk to remote language models from the terminal",
		Long: "yonderllm is a terminal client for language models that run somewhere else.\n" +
			"No weights are loaded locally: this machine draws the interface and\n" +
			"shuttles bytes, and every token is generated by a remote provider.\n\n" +
			"Run without a subcommand to open the interactive session.",
		Version:       Version,
		SilenceUsage:  true,
		SilenceErrors: true,
		// Cobra prints usage on an unknown-flag error before our handler
		// sees it; silencing both above lets Execute format failures.
		RunE: func(cmd *cobra.Command, args []string) error {
			if (e.resume != "" || e.last) && !interactiveStdin(cmd.InOrStdin()) {
				return fmt.Errorf("resume needs a terminal or a prompt through ask/run")
			}
			// A bare invocation from a terminal is the primary way in:
			// open the interactive session. Anywhere else — a pipe, a
			// script, a test harness — there is nobody to type at a
			// full-screen interface, so explain the command instead of
			// exiting 0 with no output.
			if len(args) == 0 && interactiveStdin(cmd.InOrStdin()) {
				return e.runTUI()
			}
			return cmd.Help()
		},
	}

	flags := root.PersistentFlags()
	flags.StringVar(&e.configPath, "config", "", "path to config.toml (default: per-user config directory)")
	flags.StringVarP(&e.provider, "provider", "p", "", "provider to use first (groq, gemini, openrouter, ...)")
	flags.StringVarP(&e.model, "model", "m", "", "model id for the active provider")
	flags.StringVar(&e.mode, "mode", "", "permission mode: chat, code, or agent")
	flags.IntVar(&e.maxTokens, "max-tokens", 0, "cap on output tokens per request")
	flags.IntVar(&e.dailyCap, "daily-cap", -1, "cap on requests per day (0 disables the cap)")
	flags.BoolVar(&e.yes, "yes", false, "accept agent mode's writes and commands in advance (agent mode only)")
	flags.StringVar(&e.resume, "resume", "", "resume a saved conversation")
	flags.BoolVar(&e.last, "last", false, "resume the most recently saved conversation")
	flags.StringVar(&e.save, "save", "", "save the completed conversation under this name")
	flags.BoolVar(&e.noSave, "no-save", false, "disable automatic conversation saving")
	root.MarkFlagsMutuallyExclusive("resume", "last")
	root.MarkFlagsMutuallyExclusive("save", "no-save")

	root.SetIn(e.in)
	root.SetOut(e.out)
	root.SetErr(e.errOut)

	// The help command is registered eagerly, rather than left to cobra's
	// lazy InitDefaultHelpCmd, because applyTemplates walks Commands() now
	// and cobra would not have added it yet. SetHelpCommand keeps cobra
	// from building its own; the later Remove/Add cycle is idempotent.
	helpCmd := newHelpCmd()
	root.SetHelpCommand(helpCmd)

	root.AddCommand(
		newVersionCmd(),
		newAskCmd(e),
		newRunCmd(e),
		newSessionsCmd(e),
		newModelsCmd(e),
		newProvidersCmd(e),
		newConfigCmd(e),
		helpCmd,
		newCompletionCmd(),
	)

	applyTemplates(root)
	return root
}

// Execute runs the command tree and returns a process exit code.
//
// Errors are formatted here, once, so that every failure path prints in the
// same shape and no subcommand has to remember to.
func Execute(args []string, in io.Reader, out, errOut io.Writer) int {
	e := &env{in: in, out: out, errOut: errOut}
	root := newRoot(e)

	// Cobra falls back to os.Args[1:] when SetArgs receives nil, which would
	// make a no-argument Execute parse whatever flags the host process was
	// started with. An empty non-nil slice pins it to the caller's intent.
	if args == nil {
		args = []string{}
	}
	root.SetArgs(args)

	err := root.Execute()
	switch {
	case err == nil:
		return 0
	case errors.Is(err, context.Canceled):
		fmt.Fprintln(errOut, "yonderllm: interrupted")
		return 130
	default:
		fmt.Fprintf(errOut, "yonderllm: %v\n", err)
		return 1
	}
}

// Main is the entry point wrapper used by cmd/yonderllm.
func Main() int {
	return Execute(os.Args[1:], os.Stdin, os.Stdout, os.Stderr)
}

// signalContext derives a context that is cancelled on interrupt.
//
// A streaming request holds an open HTTP body; without this, Ctrl-C would leave
// the request running until the process died. Cancelling the context closes the
// stream, and Execute turns the resulting context.Canceled into exit 130, which
// is what a shell expects from a program killed by SIGINT.
func signalContext(cmd *cobra.Command) (context.Context, context.CancelFunc) {
	return signal.NotifyContext(cmd.Context(), os.Interrupt)
}
